from __future__ import annotations

from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


TITLES = {
    "legal_notice": "Legal Notice Draft",
    "fir_draft": "FIR Draft",
    "rental_dispute_letter": "Rental Dispute Letter Draft",
}

PUNCTUATION_REPLACEMENTS = str.maketrans({
    "\u2010": "-", "\u2011": "-", "\u2012": "-", "\u2013": "-", "\u2014": "-", "\u2212": "-",
    "\u2018": "'", "\u2019": "'", "\u201a": "'", "\u201b": "'",
    "\u201c": '"', "\u201d": '"', "\u201e": '"', "\u201f": '"',
    "\u00a0": " ", "\u2026": "...",
})


def pdf_text(value: str) -> str:
    """Keep common punctuation renderable in ReportLab's built-in fonts."""
    return escape(str(value).translate(PUNCTUATION_REPLACEMENTS))


def create_pdf(document_type: str, language: str, jurisdiction: str, facts: dict[str, str]) -> bytes:
    buffer = BytesIO()
    document = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=20 * mm, leftMargin=20 * mm)
    styles = getSampleStyleSheet()
    story = [Paragraph(TITLES[document_type], styles["Title"]), Spacer(1, 10)]
    story.append(Paragraph(f"Jurisdiction: {pdf_text(jurisdiction)}", styles["Normal"]))
    story.append(Spacer(1, 10))
    for label, value in facts.items():
        story.extend([Paragraph(f"<b>{pdf_text(label.replace('_', ' ').title())}</b>", styles["Heading3"]), Paragraph(pdf_text(value), styles["BodyText"])])
        story.append(Spacer(1, 6))
    story.extend(
        [
            Spacer(1, 16),
            Paragraph(
                "DISCLAIMER: This is an informational draft generated by MicroLawyer AI. It is not legal advice, not a final legal filing, and must be reviewed with a qualified lawyer or the relevant authority before use.",
                styles["Italic"],
            ),
        ]
    )
    document.build(story)
    return buffer.getvalue()